### ISSUE TITLE
Different layers in resnext50_elastic and resnext50

### ISSUE THREAD

**Issue by D-X-Y** [allenai/elastic#5]
Would you mind to let me know why do you set a different `layers` for resnext50 and resnext50_elastic?

**Comment by csrhddlam** [comment]
Hi Xuanyi,

In short, we change it mainly to match the FLOPs of resnext50.

If we change the blocks to elastic blocks and keep the same "layers", we'll get models with the same number of parameters and fewer FLOPs, which we call sElastic models as shown in Appendix A. See Appendix A and B for more details.

Best,
Huiyu

**Comment by D-X-Y** [comment]
Thanks a lot.
