### ISSUE TITLE
Select branches?

### ISSUE THREAD

**Issue by fuyuantan** [allenai/elastic#6]

**Comment by fuyuantan** [comment]
Hi, nice job and respect!

After reading your paper, I don't understand
1) how to "let the network make decision on adjusting its process toward various resolutions at each layer". ?
2) whether the image only go through some branches in each layer, without going through other branches? If it is YES, and How to make it? Or the image go through all the branches in each layer?

It's grateful to see your reply soon.
Thank you!

**Comment by csrhddlam** [comment]
Hi,

Thanks for your interest in our work. I'd like to answer question 2 first.

2. During both training and inference, all images go through all branches in all layers. Please refer to equation 3, figure 3, or [the code](https://github.com/allenai/elastic/blob/master/models/resnext.py)  for more details.

1. Given an input image, a network processes it by activating some related filters, e.g. head detectors activate on humans, while temple detectors probably do not activate on humans. Here, by "make decision", we mean "the network may activate branches in different resolutions at
each layer". Experiments 4.1.1 verifies it. (To make it clear, other branches are always calculated, but may not be activated or relevant.)

Let me know if you have more questions.

Best,
Huiyu

**Comment by fuyuantan** [comment]
Hi,
It's happy to see your reply. It's helpful.

I have another two questions:

1.How to activate the branches? I had seen your code, but didn't find the exactly related code. Would you mind show me some code shortly?

2.What to be accorded to activate different branches? Another word, based on what to let the network to learn to activate different branches on different instances? 

Highly respect! It's grateful to see your reply soon.
Thank you!

**Comment by fuyuantan** [comment]
My question 2, in another word, why activate this branch instead of that one?Or all the branches are activated, but their scale policy scores are different?

**Comment by csrhddlam** [comment]
Hi,

1. [This](https://github.com/allenai/elastic/blob/master/models/resnext.py#L125) is exactly how an elastic block differs from a normal resnext block, in practice.

2. In your word, Yes, all the branches are activated, but their scale policy scores are different. In our word, given an input, some branches activate much more than others, which is implicit dynamic selection in our analysis. We use this term to help people understand what the model is doing and how it is different from normal CNNs. But again, all branches are computed during inference.

Thanks again for your interest in our work.

Best,
Huiyu
