### ISSUE TITLE
How to train with CIFAR?

### ISSUE THREAD

**Issue by alwayslj** [allenai/elastic#8]

**Comment by csrhddlam** [comment]
Hi,

Thanks for your interest in our work. We haven't experimented on CIFAR, but it would be straight forward to apply Elastic on a CIFAR model like ResNet. And I would recommend [this repo](https://github.com/bearpaw/pytorch-classification) for CIFAR training. All you need to do is augmenting the ResNet there with Elastic.

Huiyu

**Comment by alwayslj** [comment]
> Hi,
> 
> Thanks for your interest in our work. We haven't experimented on CIFAR, but it would be straight forward to apply Elastic on a CIFAR model like ResNet. And I would recommend [this repo](https://github.com/bearpaw/pytorch-classification) for CIFAR training. All you need to do is augmenting the ResNet there with Elastic.
> 
> Huiyu

Thank you for your prompt reply!
